#!/bin/sh
################################################################################
#      This file is part of OpenELEC - http://www.openelec.tv
#      Copyright (C) 2009-2016 Stephan Raue (stephan@openelec.tv)
#
#  OpenELEC is free software: you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation, either version 2 of the License, or
#  (at your option) any later version.
#
#  OpenELEC is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with OpenELEC.  If not, see <http://www.gnu.org/licenses/>.
################################################################################

echo "getting sources..."
  if [ ! -d linux-s805.git ]; then
    git clone https://github.com/kivutar/linux-amlogic -b master linux-s805.git
  fi

  cd linux-s805.git
    #git pull
    GIT_REV=`git log -n1 --format=%h`
  cd ..

echo "copying sources..."
  rm -rf linux-$GIT_REV
  cp -R linux-s805.git linux-$GIT_REV

echo "cleaning sources..."
  rm -rf linux-$GIT_REV/.git

echo "packing sources..."
  tar cvJf linux-$GIT_REV.tar.xz linux-$GIT_REV

echo "remove temporary sourcedir..."
  rm -rf linux-$GIT_REV
